### PR TITLE
Housekeeping

### LINKED ISSUE #5: Still maintained?
Hi there! Is this project still maintained?

Thank you!

### PR DESCRIPTION
**Pull request by n-rodriguez**
Closes https://github.com/bovender/imapcli/issues/5

Thank you!

### CODE REVIEW

**Comment by bovender** [comment]
Thanks very much! :-)

I currently have difficulties getting this branch to run in a Docker container -- most likely a PEBKAC -- would you know by any chance why this won't work?

Slightly modified Dockerfile that adds the source files to the image (rather than pulling from Github, not sure if I want to continue doing that anyway):

```docker
FROM ruby:alpine
LABEL maintainer=bovender@bovender.de
LABEL description="Command-line tool to query IMAP servers."

WORKDIR /
ADD . /imapcli
RUN apk add --no-cache git build-base && \
  cd imapcli && \
  bundle update --bundler && \
  bundle && \
  apk del build-base && \
  rm -rf /var/cache/apk/*

WORKDIR /imapcli
ENTRYPOINT ["exe/imapcli"]
```

With this, I get:

```fish
daniel@seppel9 ~/l/C/imapcli (n-rodriguez-wip/housekeeping) [1]> docker run -it imapcli
/usr/local/bundle/gems/gli-2.21.5/lib/gli.rb:14: warning: ostruct was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add ostruct to your Gemfile or gemspec to silence this warning.
bundler: failed to load command: imapcli (/usr/local/bundle/bin/imapcli)
/imapcli/exe/imapcli:8:in `<top (required)>': uninitialized constant Imapcli::CLI (NameError)

exit Imapcli::CLI.run(ARGV)
            ^^^^^
Did you mean?  Imapcli::Cli
               GLI
               CGI
        from /usr/local/bundle/bin/imapcli:25:in `load'
        from /usr/local/bundle/bin/imapcli:25:in `<top (required)>'
        from /usr/local/bundle/gems/bundler-2.5.22/lib/bundler/cli/exec.rb:58:in `load'
        from /usr/local/bundle/gems/bundler-2.5.22/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /usr/local/bundle/gems/bundler-2.5.22/lib/bundler/cli/exec.rb:23:in `run'
        from /usr/local/bundle/gems/bundler-2.5.22/lib/bundler/cli.rb:455:in `exec'
        from /usr/local/bundle/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
        from /usr/local/bundle/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/bundle/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
        from /usr/local/bundle/gems/bundler-2.5.22/lib/bundler/cli.rb:35:in `dispatch'
        from /usr/local/bundle/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
        from /usr/local/bundle/gems/bundler-2.5.22/lib/bundler/cli.rb:29:in `start'
        from /usr/local/bundle/gems/bundler-2.5.22/exe/bundle:28:in `block in <top (required)>'
        from /usr/local/bundle/gems/bundler-2.5.22/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /usr/local/bundle/gems/bundler-2.5.22/exe/bundle:20:in `<top (required)>'
        from /usr/local/bundle/bin/bundle:25:in `load'
        from /usr/local/bundle/bin/bundle:25:in `<main>'
```

This puzzles me because I would expect the line `loader.inflector.inflect 'cli' => 'CLI'` in `lib/imapcli` to prevent this error, but evidently it does not.

Funnily, I can run the program all right when I execute a shell inside the container:

```fish
daniel@seppel9 ~/l/C/imapcli (n-rodriguez-wip/housekeeping)> docker run -it --entrypoint sh imapcli
/imapcli # exe/imapcli
NAME
    imapcli - Command-line interface for IMAP servers
# ...
```

What am I missing?

**Comment by n-rodriguez** [comment]
This is weird... and I can't reproduce this issue locally :/

**Comment by n-rodriguez** [comment]
I think I get it :

```sh
 # load zeitwerk
 Zeitwerk::Loader.for_gem.tap do |loader|
-  loader.setup
   loader.inflector.inflect 'cli' => 'CLI'
+  loader.setup
 end
```

Can you please `git pull` and retry?

**Comment by n-rodriguez** [comment]
Also for Docker image build I would do :

```sh
FROM ruby:alpine
LABEL maintainer=bovender@bovender.de
LABEL description="Command-line tool to query IMAP servers."

WORKDIR /
ADD . /imapcli
RUN apk add --no-cache git build-base && \
  gem update --system && \
  cd imapcli && \
  bundle config set --local without development test && \
  bundle install && \
  apk del build-base && \
  rm -rf /var/cache/apk/*

WORKDIR /imapcli
ENTRYPOINT ["exe/imapcli"]
```

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by bovender** [comment]
Tested it and had `rspec` test it, too, looks good, thanks!

**Comment by bovender** [comment]
I've also committed the changes to the Dockerfile, however I commented out the  `bundle config` line so that I could run `rspec` in the local container.

**Pull request closed without merging**
